/* ═══════════════════════════════════════════════════════════════════
   브랜디크 포트폴리오 — 데이터
   admin.html 에서 내보낸 파일입니다. 직접 고치셔도 됩니다.
   내보낸 시각: 2026. 8. 21. 오후 3:29:53
   ═══════════════════════════════════════════════════════════════════ */

/* 작업 유형 — 전체 페이지(works.html)의 필터 버튼이 됩니다 */
const WORK_TYPES = ["로고", "캐릭터 로고", "브랜딩", "웹사이트", "패키지 · 인쇄물", "네이밍"];

const WORKS = [
  {
    title: "펜캉스",
    cat: "마케팅",
    type: "로고",
    tags: "로고",
    cover: "assets/works/penkangs-01.png",
    images: ["assets/works/penkangs-01.png", "assets/works/penkangs-02.png", "assets/works/penkangs-03.jpg", "assets/works/penkangs-04.jpg"],
    featured: true,
  },
  {
    title: "마오르 아트",
    cat: "교육",
    type: "로고",
    tags: "로고",
    cover: "assets/works/maor-art-01.png",
    images: ["assets/works/maor-art-01.png", "assets/works/maor-art-02.jpg", "assets/works/maor-art-03.jpg"],
  },
  {
    title: "신선더함",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/shinsun-deoham-01.png",
    images: ["assets/works/shinsun-deoham-01.png", "assets/works/shinsun-deoham-02.jpg", "assets/works/shinsun-deoham-03.jpg", "assets/works/shinsun-deoham-04.jpg", "assets/works/shinsun-deoham-05.jpg"],
    featured: true,
  },
  {
    title: "댕구르르",
    cat: "반려동물",
    type: "로고",
    tags: "로고",
    cover: "assets/works/daenggureure-01.png",
    images: ["assets/works/daenggureure-01.png", "assets/works/daenggureure-02.png", "assets/works/daenggureure-03.jpg", "assets/works/daenggureure-04.jpg", "assets/works/daenggureure-05.jpg"],
    featured: true,
  },
  {
    title: "캄초",
    cat: "공방",
    type: "로고",
    tags: "로고",
    cover: "assets/works/kamcho-01.png",
    images: ["assets/works/kamcho-01.png", "assets/works/kamcho-02.jpg", "assets/works/kamcho-03.jpg", "assets/works/kamcho-04.jpg", "assets/works/kamcho-05.jpg"],
    featured: true,
  },
  {
    title: "진스킨&바디",
    cat: "뷰티",
    type: "로고",
    tags: "로고",
    cover: "assets/works/jinskin-body-01.png",
    images: ["assets/works/jinskin-body-01.png", "assets/works/jinskin-body-02.jpg", "assets/works/jinskin-body-03.jpg", "assets/works/jinskin-body-04.jpg"],
  },
  {
    title: "라이언그룹",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/lion-group-01.png",
    images: ["assets/works/lion-group-01.png", "assets/works/lion-group-02.png", "assets/works/lion-group-03.jpg", "assets/works/lion-group-04.jpg", "assets/works/lion-group-05.jpg"],
  },
  {
    title: "MANS SELECTOR",
    type: "로고",
    cover: "assets/works/mans-selector-01.jpg",
    images: ["assets/works/mans-selector-01.jpg", "assets/works/mans-selector-02.jpg", "assets/works/mans-selector-03.jpg", "assets/works/mans-selector-04.jpg"],
    featured: true,
  },
  {
    title: "모아로지스",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/moalogis-01.png",
    images: ["assets/works/moalogis-01.png", "assets/works/moalogis-02.jpg", "assets/works/moalogis-03.jpg", "assets/works/moalogis-04.jpg", "assets/works/moalogis-05.jpg"],
  },
  {
    title: "오토위너스",
    cat: "자동차",
    type: "로고",
    cover: "assets/works/autowinners-01.png",
    images: ["assets/works/autowinners-01.png", "assets/works/autowinners-02.jpg", "assets/works/autowinners-03.jpg", "assets/works/autowinners-04.jpg", "assets/works/autowinners-05.jpg", "assets/works/autowinners-06.jpg"],
  },
  {
    title: "UP TO YOU",
    cat: "미용",
    type: "로고",
    tags: "로고",
    cover: "assets/works/up-to-you-01.jpg",
    images: ["assets/works/up-to-you-01.jpg", "assets/works/up-to-you-02.jpg", "assets/works/up-to-you-03.jpg", "assets/works/up-to-you-04.jpg", "assets/works/up-to-you-05.jpg"],
    featured: true,
  },
  {
    title: "맛다온",
    cat: "요리",
    type: "로고",
    tags: "로고",
    cover: "assets/works/matdaon-01.jpg",
    images: ["assets/works/matdaon-01.jpg", "assets/works/matdaon-02.jpg", "assets/works/matdaon-03.jpg", "assets/works/matdaon-04.jpg", "assets/works/matdaon-05.jpg"],
    featured: true,
  },
  {
    title: "서우비앤비",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/seowoo-bnb-01.jpg",
    images: ["assets/works/seowoo-bnb-01.jpg", "assets/works/seowoo-bnb-02.jpg", "assets/works/seowoo-bnb-03.jpg", "assets/works/seowoo-bnb-04.jpg"],
  },
  {
    title: "댕OOTD",
    cat: "반려동물",
    type: "로고",
    tags: "로고",
    cover: "assets/works/daeng-ootd-01.png",
    images: ["assets/works/daeng-ootd-01.png", "assets/works/daeng-ootd-02.png", "assets/works/daeng-ootd-03.jpg", "assets/works/daeng-ootd-04.jpg", "assets/works/daeng-ootd-05.jpg", "assets/works/daeng-ootd-06.jpg"],
    featured: true,
  },
  {
    title: "스토밍 아트",
    cat: "교육",
    type: "로고",
    tags: "로고",
    cover: "assets/works/stoming-art-01.png",
    images: ["assets/works/stoming-art-01.png", "assets/works/stoming-art-02.jpg", "assets/works/stoming-art-03.jpg", "assets/works/stoming-art-04.jpg", "assets/works/stoming-art-05.jpg"],
    featured: true,
  },
  {
    title: "TRIPOD WORKS",
    cat: "캠핑",
    type: "로고",
    cover: "assets/works/tripod-works-01.png",
    images: ["assets/works/tripod-works-01.png", "assets/works/tripod-works-02.png", "assets/works/tripod-works-03.png", "assets/works/tripod-works-04.png", "assets/works/tripod-works-05.jpg", "assets/works/tripod-works-06.jpg", "assets/works/tripod-works-07.jpg", "assets/works/tripod-works-08.jpg", "assets/works/tripod-works-09.jpg"],
    featured: true,
  },
];
