/* ═══════════════════════════════════════════════════════════════════
   브랜디크 포트폴리오 — 데이터
   admin.html 에서 내보낸 파일입니다. 직접 고치셔도 됩니다.
   내보낸 시각: 2026. 8. 21. 오후 4:11:24
   ═══════════════════════════════════════════════════════════════════ */

/* 작업 유형 — 전체 페이지(works.html)의 필터 버튼이 됩니다 */
const WORK_TYPES = ["로고", "캐릭터 로고", "브랜딩", "웹사이트", "패키지 · 인쇄물", "네이밍"];

/* 업종 목록 — 관리자 페이지의 업종 선택 항목이 됩니다 */
const WORK_CATS = ["IT", "가구", "건강", "건설", "공방", "교육", "금융", "기타", "농산", "마케팅", "문화·예술", "물류", "미용", "반려동물", "법률", "베이커리", "병원", "부동산", "뷰티", "세무·회계", "수산", "숙박", "스포츠", "약국", "여행", "요리", "유통", "음식점", "음악", "의류", "인테리어", "자동차", "잡화", "제조", "주점", "카페", "캠핑", "패션", "학원", "헬스"];

const WORKS = [
  {
    title: "펜캉스",
    cat: "마케팅",
    type: "로고",
    tags: "로고",
    cover: "assets/works/penkangs-01.png",
    images: ["assets/works/penkangs-01.png", "assets/works/penkangs-02.png", "assets/works/penkangs-03.jpg", "assets/works/penkangs-04.jpg"],
    featured: true,
  },
  {
    title: "마오르 아트",
    cat: "교육",
    type: "로고",
    tags: "로고",
    cover: "assets/works/maor-art-01.png",
    images: ["assets/works/maor-art-01.png", "assets/works/maor-art-02.jpg", "assets/works/maor-art-03.jpg"],
  },
  {
    title: "순숨",
    cat: "뷰티",
    type: "로고",
    tags: "로고",
    cover: "assets/works/sunsum-01.jpg",
    images: ["assets/works/sunsum-01.jpg", "assets/works/sunsum-03.jpg", "assets/works/sunsum-04.jpg", "assets/works/sunsum-06.jpg"],
  },
  {
    title: "신선더함",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/shinsun-deoham-01.png",
    images: ["assets/works/shinsun-deoham-01.png", "assets/works/shinsun-deoham-02.jpg", "assets/works/shinsun-deoham-03.jpg", "assets/works/shinsun-deoham-04.jpg", "assets/works/shinsun-deoham-05.jpg"],
    featured: true,
  },
  {
    title: "댕구르르",
    cat: "반려동물",
    type: "로고",
    tags: "로고",
    cover: "assets/works/daenggureure-01.png",
    images: ["assets/works/daenggureure-01.png", "assets/works/daenggureure-02.png", "assets/works/daenggureure-03.jpg", "assets/works/daenggureure-04.jpg", "assets/works/daenggureure-05.jpg"],
    featured: true,
  },
  {
    title: "캄초",
    cat: "공방",
    type: "로고",
    tags: "로고",
    cover: "assets/works/kamcho-01.png",
    images: ["assets/works/kamcho-01.png", "assets/works/kamcho-02.jpg", "assets/works/kamcho-03.jpg", "assets/works/kamcho-04.jpg", "assets/works/kamcho-05.jpg"],
    featured: true,
  },
  {
    tags: "로고",
    title: "MANS SELECTOR",
    cat: "의류",
    type: "로고",
    cover: "assets/works/mans-selector-01.jpg",
    images: ["assets/works/mans-selector-01.jpg", "assets/works/mans-selector-02.jpg", "assets/works/mans-selector-03.jpg", "assets/works/mans-selector-04.jpg"],
    featured: true,
  },
  {
    title: "UP TO YOU",
    cat: "미용",
    type: "로고",
    tags: "로고",
    cover: "assets/works/up-to-you-01.jpg",
    images: ["assets/works/up-to-you-01.jpg", "assets/works/up-to-you-02.jpg", "assets/works/up-to-you-03.jpg", "assets/works/up-to-you-04.jpg", "assets/works/up-to-you-05.jpg"],
    featured: true,
  },
  {
    title: "TRIPOD WORKS",
    cat: "캠핑",
    type: "로고",
    cover: "assets/works/tripod-works-01.png",
    images: ["assets/works/tripod-works-01.png", "assets/works/tripod-works-02.png", "assets/works/tripod-works-03.png", "assets/works/tripod-works-04.png", "assets/works/tripod-works-05.jpg", "assets/works/tripod-works-06.jpg", "assets/works/tripod-works-07.jpg", "assets/works/tripod-works-08.jpg", "assets/works/tripod-works-09.jpg"],
    featured: true,
  },
  {
    title: "오토위너스",
    cat: "자동차",
    type: "로고",
    cover: "assets/works/autowinners-01.png",
    images: ["assets/works/autowinners-01.png", "assets/works/autowinners-02.jpg", "assets/works/autowinners-03.jpg", "assets/works/autowinners-04.jpg", "assets/works/autowinners-05.jpg", "assets/works/autowinners-06.jpg"],
  },
  {
    title: "맛다온",
    cat: "음식점",
    type: "로고",
    tags: "로고",
    cover: "assets/works/matdaon-01.jpg",
    images: ["assets/works/matdaon-01.jpg", "assets/works/matdaon-02.jpg", "assets/works/matdaon-03.jpg", "assets/works/matdaon-04.jpg", "assets/works/matdaon-05.jpg"],
    featured: true,
  },
  {
    title: "라이언그룹",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/lion-group-01.png",
    images: ["assets/works/lion-group-01.png", "assets/works/lion-group-02.png", "assets/works/lion-group-03.jpg", "assets/works/lion-group-04.jpg", "assets/works/lion-group-05.jpg"],
  },
  {
    title: "서우비앤비",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/seowoo-bnb-01.jpg",
    images: ["assets/works/seowoo-bnb-01.jpg", "assets/works/seowoo-bnb-02.jpg", "assets/works/seowoo-bnb-03.jpg", "assets/works/seowoo-bnb-04.jpg"],
  },
  {
    title: "댕OOTD",
    cat: "반려동물",
    type: "로고",
    tags: "로고",
    cover: "assets/works/daeng-ootd-01.png",
    images: ["assets/works/daeng-ootd-01.png", "assets/works/daeng-ootd-02.png", "assets/works/daeng-ootd-03.jpg", "assets/works/daeng-ootd-04.jpg", "assets/works/daeng-ootd-05.jpg", "assets/works/daeng-ootd-06.jpg"],
    featured: true,
  },
  {
    title: "GRIME",
    cat: "음악",
    type: "로고",
    tags: "로고",
    cover: "assets/works/grime-01.jpg",
    images: ["assets/works/grime-01.jpg", "assets/works/grime-02.jpg", "assets/works/grime-03.jpg", "assets/works/grime-04.jpg", "assets/works/grime-05.jpg"],
  },
  {
    title: "스토밍 아트",
    cat: "교육",
    type: "로고",
    tags: "로고",
    cover: "assets/works/stoming-art-01.png",
    images: ["assets/works/stoming-art-01.png", "assets/works/stoming-art-02.jpg", "assets/works/stoming-art-03.jpg", "assets/works/stoming-art-04.jpg", "assets/works/stoming-art-05.jpg"],
  },
  {
    title: "커몬시스터즈",
    cat: "의류",
    type: "로고",
    cover: "assets/works/keomonsiseuteojeu-01.jpg",
    images: ["assets/works/keomonsiseuteojeu-01.jpg", "assets/works/keomonsiseuteojeu-02.jpg", "assets/works/keomonsiseuteojeu-03.jpg", "assets/works/keomonsiseuteojeu-04.jpg", "assets/works/keomonsiseuteojeu-05.jpg"],
  },
  {
    title: "진스킨&바디",
    cat: "뷰티",
    type: "로고",
    tags: "로고",
    cover: "assets/works/jinskin-body-01.png",
    images: ["assets/works/jinskin-body-01.png", "assets/works/jinskin-body-02.jpg", "assets/works/jinskin-body-03.jpg", "assets/works/jinskin-body-04.jpg"],
  },
  {
    title: "모아로지스",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/moalogis-01.png",
    images: ["assets/works/moalogis-01.png", "assets/works/moalogis-02.jpg", "assets/works/moalogis-03.jpg", "assets/works/moalogis-04.jpg", "assets/works/moalogis-05.jpg"],
  },
  {
    title: "HEALTH BANK",
    cat: "건강",
    type: "로고",
    tags: "로고",
    cover: "assets/works/health-bank-01.jpg",
    images: ["assets/works/health-bank-01.jpg", "assets/works/health-bank-02.jpg", "assets/works/health-bank-03.jpg", "assets/works/health-bank-04.jpg", "assets/works/health-bank-05.jpg"],
  },
  {
    title: "케이크 그림",
    cat: "베이커리",
    type: "로고",
    tags: "로고",
    cover: "assets/works/keikeu-geurim-01.png",
    images: ["assets/works/keikeu-geurim-01.png", "assets/works/keikeu-geurim-05.jpg", "assets/works/keikeu-geurim-06.jpg", "assets/works/keikeu-geurim-07.jpg", "assets/works/keikeu-geurim-08.jpg"],
  },
  {
    title: "안성배뜰",
    cat: "농산",
    type: "로고",
    tags: "로고",
    cover: "assets/works/anseongbaetteul-01.jpg",
    images: ["assets/works/anseongbaetteul-01.jpg", "assets/works/anseongbaetteul-02.jpg", "assets/works/anseongbaetteul-03.jpg", "assets/works/anseongbaetteul-04.jpg", "assets/works/anseongbaetteul-05.jpg"],
  },
  {
    title: "FROM TOP TO TOE",
    cat: "뷰티",
    type: "로고",
    tags: "로고",
    cover: "assets/works/from-top-to-toe-01.png",
    images: ["assets/works/from-top-to-toe-01.png", "assets/works/from-top-to-toe-02.jpg", "assets/works/from-top-to-toe-03.jpg", "assets/works/from-top-to-toe-04.jpg", "assets/works/from-top-to-toe-05.jpg", "assets/works/from-top-to-toe-06.jpg"],
  },
  {
    title: "노무사사무소 해담",
    cat: "법률",
    type: "로고",
    cover: "assets/works/nomusasamuso-haedam-01.png",
  },
  {
    title: "디노코코",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/dinokoko-01.png",
  },
  {
    title: "책밤",
    cat: "요리",
    type: "로고",
    cover: "assets/works/chaekbam-01.png",
  },
  {
    title: "카페 몽루",
    cat: "카페",
    type: "로고",
    tags: "로고",
    cover: "assets/works/kape-mongru-01.png",
  },
  {
    title: "태양건설",
    cat: "건설",
    type: "로고",
    tags: "로고",
    cover: "assets/works/taeyanggeonseol-01.png",
  },
  {
    title: "세종솔루션",
    cat: "유통",
    type: "로고",
    tags: "로고",
    cover: "assets/works/sejongsolrusyeon-01.png",
  },
  {
    title: "디딤돌 정형외과",
    cat: "병원",
    type: "로고",
    cover: "assets/works/didimdol-jeonghyeongoegwa-01.png",
  },
  {
    title: "한일탑내과",
    cat: "병원",
    type: "로고",
    cover: "assets/works/haniltapnaegwa-01.png",
  },
];
